export const CEREBRO_BASE_URL = process.env.EXPO_PUBLIC_CEREBRO_BASE_URL;
export const EVENTS_BASE_URL = process.env.EXPO_PUBLIC_EVENTS_BASE_URL;
export const PROFILE_BASE_URL = process.env.EXPO_PUBLIC_PROFILE_BASE_URL;
